### ISSUE TITLE
Will your build script support docker buildx?

### ISSUE THREAD

**Issue by gramss** [athackst/dockerfiles#177]
Hello,

thank you for your great tool.
We are currently trying to build multi-arch images with your Dockerfiles and script.
Unfortunately, when building your Dockerfiles directly, it only generates one big latest tag.

We think that it would be needed to update your build script for having docker buildx support to automatically generate your multi-stage images.
Are you interested in such a feature? Do you have information that you can point us towards? Are you interested in a PR regarding this topic?

Kind regards

**Comment by athackst** [comment]
Hello!

I would definitely accept a PR that makes it buildx compliant.

Today you can generate a specific target through `docker build --target <target name> -f <dockerfile> -t <tag name> .` so you can already specify a target within the image.

buildx would be adding multi-arch support which would be new.
