### ISSUE TITLE
Add multiplatform support to docker images

### ISSUE THREAD

**Issue by Nils-ChristianIseke** [athackst/dockerfiles#275]
It would be nice if your docker images would also support ARM-Architecture :) https://docs.docker.com/build/building/multi-platform/.

**Comment by athackst** [comment]
I'm using docker-py which unfortunately doesn't support buildx https://github.com/docker/docker-py/issues/2230

I'll have to figure out another approach.

**Comment by athackst** [comment]
Which platform are you looking to get?

**Comment by athackst** [comment]
Ok, it should be publishing arm64 version to docker now
