### ISSUE TITLE
Upgrade base NVIDIA images due to deprecation

### ISSUE THREAD

**Issue by DerProfessor** [athackst/dockerfiles#277]
Hi there,
I noticed an important deprecation notice from NVIDIA when starting the foxy NVIDIA Container (tag: `docker.io/althack/ros2:foxy-cuda-full`), see below for the concrete output. It seems that a lot of older Cuda containers are being deprecated and are scheduled for deletion ([link to announcement](https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md)). This affects the Cuda `11.7.0` containers.
I believe a good solution would be to either upgrade the NVIDIA base image from Cuda `11.7.0` to either `11.7.1` or `11.8.0` . I think this affects only the Cuda images for ros2 foxy, galactic and humble.

Deprecation notice:
```
*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md
```

**Comment by athackst** [comment]
Would you be able to test?

**Comment by DerProfessor** [comment]
Hi,
I managed to test the build process of the foxy-cuda and humble-cuda images. Both built successfully on my machine using the provided devcontainer in this repository. I tested both `11.7.1` and `11.8.0` versions and they built successfully. I already created a corresponding pull request which merges the cuda `11.8.0` base image version.
