### ISSUE TITLE
unable to install gazebo

### ISSUE THREAD

**Issue by openSourceBugs** [athackst/dockerfiles#392]
I am on raspberry pi 4 (buster) trying to build an image from the humble dockerfile and get:
The following packages have unmet dependencies:
ros-humble-gazebo-dev : Depends: gazebo but it is not installabe
                                           Depends: libgazebo-dev but it is not installable

**Comment by athackst** [comment]
I realized OSRF moved to gz as the default pairing,  I'm going to assume updating to gz fixes your issue.  Feel free to re-open if you continue to have errors.
