### ISSUE TITLE
ROS_DISTRO env variable not set anymore

### ISSUE THREAD

**Issue by MoritzKlischatAB** [athackst/dockerfiles#500]
It seems like with the latest commit the ROS_DISTRO env variable amongst others is empty now.
I suspect it's due to this commit 96362dd8cabe47093b2274991c60a8f252806707

**Comment by athackst** [comment]
I reverted to avoid breaking people - but I want to understand the issue better.  The ROS_DISTRO env variable should have been set in interactive non-login shells (which is how I use these) - What wasn't able to access the variable? Can you provide steps to reproduce?

**Comment by MoritzKlischatAB** [comment]
In a Dockerfile based on this image the env variable is not visible
